title: HackinSec Tools
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
logo: https://dorks.hackinsec.com/HACKINSEC-11-16-2023.gif
color_scheme: dark
favicon_ico: https://dorks.hackinsec.com/HACKINSEC-11-16-2023.gif
url: https://rohsec.github.io/bugbountytools.hackinsec.com

aux_links:
  ğ˜ğğœğ—¦ğ¨ğ—–: https://x.com/rohsec
